# Generated by Django 4.0.4 on 2022-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.TextField(max_length=50)),
                ('beskrivelse', models.TextField()),
                ('kategori', models.TextField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('tilbehør', models.TextField(max_length=100)),
                ('link1', models.URLField(blank=True, null=True)),
                ('link2', models.URLField(blank=True, null=True)),
                ('pris', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
