# Generated by Django 4.0.4 on 2022-05-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0002_kategori_alter_hobby_img_remove_hobby_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slagsmodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='slags', to='fritid.hobby'),
        ),
    ]
