# Generated by Django 4.0.4 on 2022-05-13 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0004_rename_name_kategori_titel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kommentar', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
