# Generated by Django 4.0.4 on 2022-05-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0005_kommentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='slagsmodel',
            name='by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='slagsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='slagsmodel',
            name='navn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='img',
            field=models.ImageField(upload_to='media/menu_images/'),
        ),
        migrations.AlterField(
            model_name='slagsmodel',
            name='pris',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
