# Generated by Django 4.0.4 on 2022-05-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0007_alter_hobby_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='img',
            field=models.ImageField(upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='titel',
            field=models.CharField(max_length=50),
        ),
    ]
