# Generated by Django 4.0.4 on 2022-05-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0008_alter_hobby_img_alter_hobby_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='img',
            new_name='image',
        ),
    ]
